### ISSUE TITLE
Getting FileNotFoundException "grpc_csharp_ext.x86.dll"

### ISSUE THREAD

**Issue by erikswed** [GoogleCloudPlatform/getting-started-dotnet#114]
Following instruktions and pressing F5 in Visual Studio gave me this. Visual Studio work well for many other ASP.NET Core project so this was a surprise. Searching for a solution did not give much 

> System.IO.FileNotFoundException
>   HResult=0x80070002
>   Message=Error loading native library. Not found in any of the possible locations: 
>   C:\Users\user\Source\Repos\getting-started-dotnet\aspnet\3-binary-data\bin\grpc_csharp_ext.x86.dll,

>   C:\Users\user\Source\Repos\getting-started-dotnet\aspnet\3-binary-data\bin\runtimes/win/native\grpc_csharp_ext.x86.dll,
>   C:\Users\user\Source\Repos\getting-started-dotnet\aspnet\3-binary-data\bin\../..\runtimes/win/native\grpc_csharp_ext.x86.dll

>   Source=Grpc.Core
>   StackTrace:
>    at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
>    at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
>    at Grpc.Core.Internal.NativeExtension.Load()
>    at Grpc.Core.Internal.NativeExtension..ctor()
>    at Grpc.Core.Internal.NativeExtension.Get()
>    at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
>    at Grpc.Core.GrpcEnvironment..ctor()
>    at Grpc.Core.GrpcEnvironment.AddRef()
>    at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
>    at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials, IEnumerable`1 options)
>    at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, ChannelCredentials credentials)
>    at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint)
>    at Google.Cloud.Datastore.V1.DatastoreClient.Create(ServiceEndpoint endpoint, DatastoreSettings settings)
>    at Google.Cloud.Datastore.V1.DatastoreDb.Create(String projectId, String namespaceId, DatastoreClient client)
>    at GoogleCloudSamples.Models.DatastoreBookStore..ctor(String projectId) in C:\Users\user\Source\Repos\getting-started-dotnet\aspnet\3-binary-data\Models\DatastoreBookStore.cs:line 86
>    at GoogleCloudSamples.UnityConfig.RegisterTypes(IUnityContainer container) in C:\Users\user\Source\Repos\getting-started-dotnet\aspnet\3-binary-data\App_Start\UnityConfig.cs:line 110
>    at GoogleCloudSamples.UnityConfig.<>c.<.cctor>b__8_0() in C:\Users\user\Source\Repos\getting-started-dotnet\aspnet\3-binary-data\App_Start\UnityConfig.cs:line 53
>    at System.Lazy`1.CreateValue()

**Comment by erikswed** [comment]
Everything works. This went away by itself

**Comment by amanda-tarafa** [comment]
Closing now as all seems to be working.
